// Code generated by sgoiter emit go127 from sgoiter/testdata/c/array_i64.c.
// DO NOT EDIT.

package arrayi64

func Sort(a []int64, n int) {
	var v2 int
	var v3 int
	v2 = 0
	for v2 < n {
		v3 = 0
		for v3 < (n - 1) {
			if a[v3] > a[(v3+1)] {
				v17 := a[v3]
				v19 := v3 + 1
				a[v3] = a[v19]
				a[v19] = v17
			}
			v3++
		}
		v2++
	}
}
