include:
  - docker/service/mysql.yml
  - docker/service/postgres.yml

services:
  phpscript:
    image: titpetric/phpscript:latest
    env_file: .env.docker
    ports:
      - 8080:8080
    volumes:
      - $PWD/demos/dbadmin/:/app

  php:
    image: php:8.5
    ports:
      - 8081:8081
    volumes:
      - $PWD/demos/dbadmin/:/app
    working_dir: /app
    command: [php, -S, "0:8081"]