include:
  - docker/service/mysql.yml
  - docker/service/postgres.yml

services:
  phpscript:
    image: titpetric/phpscript:latest
    env_file: .env.docker
    networks:
      - projects-ingress
    labels:
      caddy: dbadmin.localhost
      caddy.reverse_proxy: "{{upstreams 8080}}"
    volumes:
      - $PWD/demos/dbadmin/:/app

networks:
  projects-ingress:
    external: true
