package list

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/titpetric/phpscript/internal/apidoc"
	"github.com/titpetric/phpscript/runner"
	"github.com/titpetric/phpscript/stdlib"
)

// Symbol is one name the runtime answers to, as a script would type it.
type Symbol struct {
	Kind      string // "function", "class", "method" or "constant"
	Name      string
	Signature string // PHP declaration, or the value for a constant
}

// Stdlib returns everything the standard CLI runtime registers: the functions,
// the classes and their methods, and the constants.
//
// It answers from the runtime rather than from a checked-in list, so a build
// reports what that build actually binds. What it cannot report is the doc
// comment written next to each registration, or the PHP spelling of a
// parameter name: both are read out of the Go source, which a shipped binary
// does not carry. Those live in docs/reference/extensions/implemented-apis.md,
// generated by the same reflection plus a source scan.
func Stdlib() []Symbol {
	rt := stdlibRuntime()
	funcs, classes := apidoc.Reflect(rt)

	symbols := make([]Symbol, 0, len(funcs)+len(classes)+len(rt.DefinedConstants()))
	for _, f := range funcs {
		symbols = append(symbols, Symbol{
			Kind:      "function",
			Name:      f.Name,
			Signature: f.Name + "(" + paramTypes(f.Params) + "): " + f.Returns,
		})
	}
	// The class rows come from DeclaredClasses rather than from the reflected
	// constructors, because the two do not answer the same question. A script
	// can write new stdClass(), which has no Go constructor to reflect, and a
	// name that shares its constructor with others is still a name a script
	// types. This is what makes the listing agree with what phpscript info
	// counts.
	byName := map[string]apidoc.Class{}
	for _, c := range classes {
		for _, name := range append([]string{c.Name}, c.Aliases...) {
			byName[name] = c
		}
		for _, m := range c.Methods {
			symbols = append(symbols, Symbol{
				Kind:      "method",
				Name:      c.Name + "::" + m.Name,
				Signature: c.Name + "::" + m.Name + "(" + paramTypes(m.Params) + "): " + m.Returns,
			})
		}
	}
	for _, name := range rt.DeclaredClasses() {
		c, ok := byName[name]
		if !ok {
			symbols = append(symbols, Symbol{Kind: "class", Name: name, Signature: "new " + name + "()"})
			continue
		}
		symbols = append(symbols, Symbol{
			Kind:      "class",
			Name:      name,
			Signature: "new " + name + "(" + paramTypes(c.Params) + ")",
		})
	}
	for name, value := range rt.DefinedConstants() {
		symbols = append(symbols, Symbol{Kind: "constant", Name: name, Signature: constantValue(value)})
	}

	sort.Slice(symbols, func(i, j int) bool {
		if symbols[i].Kind != symbols[j].Kind {
			return symbols[i].Kind < symbols[j].Kind
		}
		return symbols[i].Name < symbols[j].Name
	})
	return symbols
}

// StdlibMarkdown renders the registered surface as a markdown table, the same
// shape Markdown gives a source listing.
func StdlibMarkdown(symbols []Symbol) string {
	rows := make([][]string, 0, len(symbols))
	for _, s := range symbols {
		rows = append(rows, []string{s.Kind, s.Name, cell(s.Signature)})
	}
	return markdownTable([]string{"Kind", "Name", "Signature"}, rows)
}

// stdlibRuntime builds the runtime the phpscript CLI runs, so the listing is
// what a script sees. The request-aware functions (header, http_response_code,
// getallheaders) are installed per request rather than by stdlib.Register, and
// a server-targeted script still names them, so an empty request context
// registers them for the listing. This is the recipe scripts/list-apis uses.
func stdlibRuntime() *runner.Runtime {
	rt := runner.New(io.Discard, runner.Options{SAPI: "cli", RootFS: os.DirFS(".")})
	stdlib.Register(rt)
	stdlib.RegisterFS(rt, ".")
	runner.NewContext().Register(rt)
	return rt
}

// paramTypes renders a parameter list as types alone.
//
// The names reflection recovers are invented from the Go types, so a binding
// with two string parameters publishes them as $string1 and $string2 here
// however carefully they are named at the registration site. Printing an
// invented name is worse than printing none: it reads as the argument's real
// spelling, which only the source scan behind implemented-apis.md knows. A
// by-reference slot has no type to print and keeps its ampersand.
func paramTypes(params []apidoc.Param) string {
	parts := make([]string, 0, len(params))
	for _, p := range params {
		switch {
		case p.ByRef:
			parts = append(parts, "&$"+p.Name)
		case p.Variadic:
			parts = append(parts, p.Type+" ...")
		default:
			parts = append(parts, p.Type)
		}
	}
	return strings.Join(parts, ", ")
}

// constantValue renders a constant's value the way a script would write it.
// Only the scalar shapes occur; anything else is reported by its Go rendering
// rather than guessed at.
func constantValue(value any) string {
	switch v := value.(type) {
	case string:
		// Quoted rather than concatenated: PHP_EOL is a newline, and a
		// raw one would break the row it is printed in.
		return strconv.Quote(v)
	case bool:
		if v {
			return "true"
		}
		return "false"
	case nil:
		return "null"
	}
	return fmt.Sprint(value)
}
