runner:
  work_dir: "."
  writable_paths: []

flatstack:
  enabled: false

routes:
  enabled: true

status:
  enabled: true
  options:
    ring_buffer_size: 100
    top_requests: 20
    track_memory_use: true

env:
  - "PLATFORM_DB_SQLITE_TEST=sqlite://:memory:"
