-- user_session: Server-side state of one logged-in browser session.
--
-- Session\Manager stores exactly one opaque string and its only writer is
-- start(), which mints a fresh cookie every time it is called. So the string
-- it stores is this row's token, an immutable pointer, and every mutable bit
-- of session state is a column here. Switching connection or turning
-- destructive mode on is an UPDATE, and the cookie is never touched.
--
-- token and csrf_token are generated by SQLite with lower(hex(randomblob(16))),
-- because PHP in this runtime has no CSPRNG. The cookie is already random; the
-- token only has to be unguessable enough that a session file surviving a
-- rebuilt database cannot land on a recycled row.
--
-- destructive_until is written as datetime('now','+900 seconds') and compared
-- in SQL. Nothing in this application formats or parses a timestamp in PHP.
--
-- flash is a single post-redirect message slot. There is no setcookie() in
-- this runtime and the session cookie is spoken for, so there is nowhere else
-- to put one that is not a query parameter.
--
-- Rows are pruned by expires_at; logout sets is_revoked rather than deleting,
-- so a replayed cookie is answered by a row that says no.

CREATE TABLE user_session (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	token TEXT NOT NULL DEFAULT '',
	csrf_token TEXT NOT NULL DEFAULT '',
	user_id INTEGER NOT NULL DEFAULT 0,
	connection_id INTEGER NOT NULL DEFAULT 0,
	schema_name TEXT NOT NULL DEFAULT '',
	is_destructive BOOLEAN NOT NULL DEFAULT 0,
	destructive_until DATETIME,
	is_revoked BOOLEAN NOT NULL DEFAULT 0,
	remote_addr TEXT NOT NULL DEFAULT '',
	user_agent TEXT NOT NULL DEFAULT '',
	flash TEXT NOT NULL DEFAULT '',
	expires_at DATETIME,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uidx_user_session_token ON user_session(token);
CREATE INDEX IF NOT EXISTS idx_user_session_user_id_created_at ON user_session(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_user_session_connection_id ON user_session(connection_id);
CREATE INDEX IF NOT EXISTS idx_user_session_expires_at ON user_session(expires_at);
