package lint

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/titpetric/phpscript/internal/table"
)

func TestRunPrintsMarkdownResultsAndSummary(t *testing.T) {
	dir := t.TempDir()
	writeLintFile(t, dir, "fail.php", `<?php class Foo {`)
	writeLintFile(t, dir, "pass.php", `<?php echo "ok";`)
	writeLintFile(t, dir, "warn.php", `<?php if ($value = true) {}`)

	var out bytes.Buffer
	err := run([]string{dir}, Options{}, &out)
	if err == nil {
		t.Fatal("run returned nil error with a failing file")
	}

	got := collapse(out.String())
	for _, want := range []string{
		"| Status | File | Line | Message |",
		"| FAIL | " + filepath.Join(dir, "fail.php") + " | 1 | parse error:",
		"| PASS | " + filepath.Join(dir, "pass.php") + " | | No lint findings |",
		"| WARN | " + filepath.Join(dir, "warn.php") + " | 1 | assignment in conditional statement |",
		"Passing 1, with 1 warnings, 1 failing",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("output does not contain %q:\n%s", want, out.String())
		}
	}
}

func TestRunFlatstackUsesOneResultPerFile(t *testing.T) {
	dir := t.TempDir()
	writeLintFile(t, dir, "pass.php", `<?php echo "ok";`)
	writeLintFile(t, dir, "warn.php", `<?php if ($value = true) {}`)

	var out bytes.Buffer
	if err := run([]string{dir}, Options{Flatstack: true}, &out); err != nil {
		t.Fatalf("run returned an error: %v", err)
	}

	got := out.String()
	if strings.Count(got, "| PASS ") != 1 {
		t.Errorf("got duplicate or missing passing rows:\n%s", got)
	}
	if !strings.Contains(got, "[flatstack compatible]") {
		t.Errorf("flatstack passing result is missing:\n%s", got)
	}
	if !strings.Contains(got, "Passing 1, with 1 warnings, 0 failing") {
		t.Errorf("unexpected summary:\n%s", got)
	}
}

// TestRunWritesMarkdownReport checks the -o file against the markdown that a
// redirected stdout produces: the report is the same table plus a header, so
// one run can print to a terminal and record the findings at once.
func TestRunWritesMarkdownReport(t *testing.T) {
	dir := t.TempDir()
	writeLintFile(t, dir, "warn.php", `<?php if ($value = true) {}`)
	output := filepath.Join(dir, "report.md")

	var out bytes.Buffer
	if err := run([]string{dir}, Options{Output: output}, &out); err != nil {
		t.Fatalf("run returned an error: %v", err)
	}

	report, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	got := string(report)
	if !strings.HasPrefix(got, "# Lint findings\n\n<!-- Generated by: phpscript lint -o ") {
		t.Errorf("report is missing its header:\n%s", got)
	}
	if !strings.Contains(got, out.String()) {
		t.Errorf("report does not contain the stdout table:\n%s\nwant:\n%s", got, out.String())
	}
}

func TestRunReportsAnsiTableOnATerminal(t *testing.T) {
	dir := t.TempDir()
	writeLintFile(t, dir, "warn.php", `<?php if ($value = true) {}`)

	// A pipe is not a terminal, so the table has to be built directly to check
	// what a terminal would be given.
	var buf bytes.Buffer
	tbl := newTable(&buf, false)
	tbl.Row(table.Colored(statusColor(statusWarn), statusWarn), table.Text("warn.php"), table.Text("1"), table.Text("finding"))
	tbl.Flush()

	got := buf.String()
	for _, want := range []string{table.BoxTopLeft, table.ColorHeader + "Status", table.ColorAmber + "WARN"} {
		if !strings.Contains(got, want) {
			t.Errorf("table does not contain %q:\n%q", want, got)
		}
	}
}

// collapse squeezes the runs of padding a table adds, so an assertion names
// the cells of a row rather than their column widths.
func collapse(value string) string {
	return strings.Join(strings.Fields(value), " ")
}

func writeLintFile(t *testing.T, dir, name, src string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
}
