package test

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// teeResultTable forwards every call to each table, so one run prints a
// terminal table to stdout and writes a markdown report to a file.
type teeResultTable []resultTable

func (t teeResultTable) writeGroup(dir string, labels []string) {
	for _, table := range t {
		table.writeGroup(dir, labels)
	}
}

func (t teeResultTable) writeResult(r *fixtureRun) {
	for _, table := range t {
		table.writeResult(r)
	}
}

func (t teeResultTable) closeGroup(totals groupTotals) {
	for _, table := range t {
		table.closeGroup(totals)
	}
}

func (t teeResultTable) writeSummary(passed, failed, total int, duration time.Duration) {
	for _, table := range t {
		table.writeSummary(passed, failed, total, duration)
	}
}

// teeMatrixTable is teeResultTable for the cross-runner matrix.
type teeMatrixTable []matrixTable

func (t teeMatrixTable) writeGroup(dir string, labels []string) {
	for _, table := range t {
		table.writeGroup(dir, labels)
	}
}

func (t teeMatrixTable) writeRow(row matrixRow) {
	for _, table := range t {
		table.writeRow(row)
	}
}

func (t teeMatrixTable) closeGroup(totals groupTotals) {
	for _, table := range t {
		table.closeGroup(totals)
	}
}

func (t teeMatrixTable) writeSummary(passed, failed, total int, duration time.Duration) {
	for _, table := range t {
		table.writeSummary(passed, failed, total, duration)
	}
}

// writeReportHeader opens a generated markdown report with its title, the
// command that produced it, and a sentence naming what it covers. The
// provenance line is derived from the invocation rather than hardcoded, so it
// always names the job that actually wrote the file.
func writeReportHeader(w io.Writer, argv []string) {
	command := strings.Join(append([]string{"phpscript"}, argv...), " ")

	fmt.Fprint(w, "# Test fixtures\n\n")
	fmt.Fprintf(w, "<!-- Generated by: %s -->\n\n", command)
	fmt.Fprint(w, "Every `.phpt` fixture in the suite, one table per folder. A fixture states a\n")
	fmt.Fprint(w, "behavior and records what PHP itself produces for the same source, so a table\n")
	fmt.Fprint(w, "below is a compatibility report rather than a record of what phpscript printed\n")
	fmt.Fprint(w, "last. See [testing.md](./testing.md) for the fixture format and how to add one.\n\n")
}

// openReport creates the -o markdown sink and writes its header. It runs
// before the first fixture, so an unwritable path fails the command
// immediately rather than after the whole suite has executed.
func openReport(opts Options, args []string) (*os.File, error) {
	if opts.Output == "" {
		return nil, nil
	}
	file, err := os.Create(opts.Output)
	if err != nil {
		return nil, fmt.Errorf("create output: %w", err)
	}
	writeReportHeader(file, reportArgs(opts, args))
	return file, nil
}

// reportArgs reconstructs the test invocation for the provenance comment.
func reportArgs(opts Options, args []string) []string {
	argv := []string{"test"}
	if opts.Matrix {
		argv = append(argv, "--matrix")
	}
	if opts.Profile {
		argv = append(argv, "--profile")
	}
	if opts.Output != "" {
		argv = append(argv, "-o", filepath.ToSlash(opts.Output))
	}
	return append(argv, args...)
}
