package test_test

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/titpetric/phpscript/cmd/phpscript/test"
	"github.com/titpetric/phpscript/tests"
)

func TestMain(m *testing.M) {
	tests.TestMain(m)
}

func TestRunCommandJSON(t *testing.T) {
	ctx := context.Background()

	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = w
	errRun := test.Run(ctx, []string{"../../../tests/fixtures/exceptions/die_exit.phpt"}, test.Options{JSON: true})
	w.Close()
	os.Stdout = old
	var buf bytes.Buffer
	_, _ = buf.ReadFrom(r)
	if errRun != nil {
		t.Fatalf("unexpected error running test command: %v", errRun)
	}

	var report struct {
		Total   int `json:"total"`
		Passed  int `json:"passed"`
		Results []struct {
			Passed bool `json:"passed"`
		} `json:"results"`
	}
	if err := json.Unmarshal(buf.Bytes(), &report); err != nil {
		t.Fatalf("json: %v\n%s", err, buf.String())
	}
	if report.Total < 1 || report.Passed < 1 {
		t.Fatalf("report = %+v", report)
	}
}

// TestRunCommandOutputFile covers -o end to end over more than one area, which
// is what the atkins report job does.
func TestRunCommandOutputFile(t *testing.T) {
	reportPath := filepath.Join(t.TempDir(), "report.md")

	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = w
	errRun := test.Run(context.Background(), []string{
		"../../../tests/fixtures/exceptions/die_exit.phpt",
		"../../../tests/fixtures/arrays/sort.phpt",
	}, test.Options{JSON: true, Output: reportPath, Parallel: 2})
	w.Close()
	os.Stdout = old
	io.Copy(io.Discard, r)
	if errRun != nil {
		t.Fatalf("unexpected error running test command: %v", errRun)
	}

	data, err := os.ReadFile(reportPath)
	if err != nil {
		t.Fatalf("read report: %v", err)
	}
	report := string(data)
	for _, want := range []string{
		"# Test fixtures",
		"<!-- Generated by: phpscript test --parallel 2 -o ",
		"/tests/fixtures/exceptions\n",
		"/tests/fixtures/arrays\n",
		"| PASS | sort.phpt",
		"| PASS | die_exit.phpt",
		"## Summary",
		"| **Total** ",
	} {
		if !strings.Contains(report, want) {
			t.Errorf("report is missing %q:\n%s", want, report)
		}
	}
}

// TestRunCommandAppRoot covers --autoload and --include: a fixture reaches a
// function the include file defines and a class the autoload folder holds,
// with neither named in the fixture body. The bare invocation (no paths) is
// what discovers the tree, which also covers the recursive default.
func TestRunCommandAppRoot(t *testing.T) {
	tmp := t.TempDir()
	write := func(name, content string) {
		t.Helper()
		p := filepath.Join(tmp, name)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	// The include file is the whole mechanism now: it pulls in the helper and
	// the class, the way an application's bootstrap pulls in composer's
	// autoloader. There is no --autoload folder flag to do half of it.
	write("autoload.php", "<?php\n\ninclude \"lib/functions.php\";\ninclude \"code/Acme/Thing.php\";\n")
	write("lib/functions.php", "<?php\n\nfunction app_name()\n{\n\treturn \"acme\";\n}\n")
	write("code/Acme/Thing.php", "<?php\n\nnamespace Acme;\n\nclass Thing\n{\n\tpublic function greet()\n\t{\n\t\treturn \"hello\";\n\t}\n}\n")
	write("suite/prelude.phpt", `name: prelude reaches include and autoload
description: >
  The include file defines app_name through a nested include, and the class
  loads lazily from the autoload folder; the fixture names neither.
---
<?php

$thing = new \Acme\Thing();
echo $thing->greet(), " ", app_name(), "\n";
---
hello acme
`)
	write("plain/noprelude.phpt", `name: missing include is skipped
description: >
  An include file that is not there is not an error: the run carries on and
  the fixture answers for itself. It names nothing the include would have
  brought, because with --include as the only resolution mechanism there is
  nothing else to fall back to.
---
<?php

echo "hello\n";
---
hello
`)

	t.Chdir(tmp)

	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = w
	errAll := test.Run(context.Background(), nil, test.Options{Include: "autoload.php"})
	errMissing := test.Run(context.Background(), []string{"plain"}, test.Options{Include: "missing.php"})
	w.Close()
	os.Stdout = old
	io.Copy(io.Discard, r)

	if errAll != nil {
		t.Errorf("bare run with --include autoload.php: %v", errAll)
	}
	if errMissing != nil {
		t.Errorf("run with a missing include file: %v", errMissing)
	}
}
