package test_test

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/titpetric/phpscript/cmd/phpscript/test"
	"github.com/titpetric/phpscript/tests"
)

func TestMain(m *testing.M) {
	tests.TestMain(m)
}

func TestRunCommandJSON(t *testing.T) {
	ctx := context.Background()
	tmpDir := t.TempDir()
	cpuPath := filepath.Join(tmpDir, "cpu.pprof")
	memPath := filepath.Join(tmpDir, "mem.pprof")

	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = w
	errRun := test.Run(ctx, []string{"../../../tests/fixtures/exceptions/die_exit.phpt"}, test.Options{
		JSON:       true,
		CPUProfile: cpuPath,
		MemProfile: memPath,
	})
	w.Close()
	os.Stdout = old
	var buf bytes.Buffer
	_, _ = buf.ReadFrom(r)
	if errRun != nil {
		t.Fatalf("unexpected error running test command: %v", errRun)
	}

	var report struct {
		Total   int `json:"total"`
		Passed  int `json:"passed"`
		Results []struct {
			Passed bool `json:"passed"`
		} `json:"results"`
	}
	if err := json.Unmarshal(buf.Bytes(), &report); err != nil {
		t.Fatalf("json: %v\n%s", err, buf.String())
	}
	if report.Total < 1 || report.Passed < 1 {
		t.Fatalf("report = %+v", report)
	}
	if _, err := os.Stat(cpuPath); err != nil {
		t.Fatalf("cpuprofile: %v", err)
	}
	if _, err := os.Stat(memPath); err != nil {
		t.Fatalf("memprofile: %v", err)
	}
}

// TestRunCommandOutputFile covers -o end to end over more than one area, which
// is what the atkins report job does.
func TestRunCommandOutputFile(t *testing.T) {
	reportPath := filepath.Join(t.TempDir(), "report.md")

	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = w
	errRun := test.Run(context.Background(), []string{
		"../../../tests/fixtures/exceptions/die_exit.phpt",
		"../../../tests/fixtures/arrays/sort.phpt",
	}, test.Options{JSON: true, Output: reportPath, Parallel: 2})
	w.Close()
	os.Stdout = old
	io.Copy(io.Discard, r)
	if errRun != nil {
		t.Fatalf("unexpected error running test command: %v", errRun)
	}

	data, err := os.ReadFile(reportPath)
	if err != nil {
		t.Fatalf("read report: %v", err)
	}
	report := string(data)
	for _, want := range []string{
		"# Test fixtures",
		"<!-- Generated by: phpscript test --parallel 2 -o ",
		"/tests/fixtures/exceptions\n",
		"/tests/fixtures/arrays\n",
		"| PASS | sort.phpt",
		"| PASS | die_exit.phpt",
		"## Summary",
		"| **Total** ",
	} {
		if !strings.Contains(report, want) {
			t.Errorf("report is missing %q:\n%s", want, report)
		}
	}
}
