package apidoc

import (
	"fmt"
	"sort"
	"strings"
)

// header carries the regeneration instructions; the tone skill and
// docs/testing.md point at the atkins job that runs the generator.
const header = `# Implemented PHP APIs

<!-- Generated by: go run ./scripts/list-apis > docs/reference/extensions/implemented-apis.md -->

This file lists the functions and classes the standard phpscript CLI runtime
registers, grouped by the Go package each binding lives in. The comment over a
binding's registration site (or the godoc of the function it registers) is the
line shown here, and the signature is derived from the Go implementation.
Regenerate with ` + "`atkins test:introspection`" + ` after changing a registration
or its comment; docs/naming-conventions.md documents the comment convention.

`

// render produces the implemented-apis markdown.
func render(funcs []Func, classes []Class) string {
	var b strings.Builder
	b.WriteString(header)

	b.WriteString("## Functions\n\n")
	for _, pkg := range packageNames(funcs) {
		fmt.Fprintf(&b, "### %s\n\n", pkg)
		renderPackage(&b, selectPackage(funcs, pkg))
	}

	b.WriteString("## Classes\n\n")
	for _, c := range classes {
		renderClass(&b, c)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// packageNames returns the sorted set of Go packages that register functions.
func packageNames(funcs []Func) []string {
	seen := map[string]bool{}
	names := []string{}
	for _, f := range funcs {
		pkg := f.Package
		if pkg == "" {
			pkg = "unattributed"
		}
		if !seen[pkg] {
			seen[pkg] = true
			names = append(names, pkg)
		}
	}
	sort.Strings(names)
	return names
}

func selectPackage(funcs []Func, pkg string) []Func {
	out := []Func{}
	for _, f := range funcs {
		p := f.Package
		if p == "" {
			p = "unattributed"
		}
		if p == pkg {
			out = append(out, f)
		}
	}
	return out
}

// renderPackage writes one package's functions, subdivided by the register*
// function that installed them when the package has more than one area.
func renderPackage(b *strings.Builder, funcs []Func) {
	areas := map[string][]Func{}
	names := []string{}
	for _, f := range funcs {
		if _, ok := areas[f.Area]; !ok {
			names = append(names, f.Area)
		}
		areas[f.Area] = append(areas[f.Area], f)
	}
	sort.Strings(names)

	if len(names) == 1 {
		renderFuncs(b, funcs)
		return
	}
	for _, area := range names {
		title := area
		if title == "" {
			title = "other"
		}
		fmt.Fprintf(b, "#### %s\n\n", title)
		renderFuncs(b, areas[area])
	}
}

func renderFuncs(b *strings.Builder, funcs []Func) {
	sort.Slice(funcs, func(i, j int) bool { return funcs[i].Name < funcs[j].Name })
	for _, f := range funcs {
		b.WriteString("```php\n")
		writeComment(b, f.Comment, "")
		// A Class::method name is not declarable with the function keyword;
		// it is cited the way a script calls it.
		if strings.Contains(f.Name, "::") {
			fmt.Fprintf(b, "%s(%s): %s\n", f.Name, paramList(f.Params), f.Returns)
		} else {
			fmt.Fprintf(b, "function %s(%s): %s\n", f.Name, paramList(f.Params), f.Returns)
		}
		b.WriteString("```\n\n")
	}
}

// renderClass writes one class as a PHP stub: constructor first, then the
// methods reflected from the Go type it constructs.
func renderClass(b *strings.Builder, c Class) {
	fmt.Fprintf(b, "### `%s`\n\n", c.Name)
	if c.Package != "" {
		fmt.Fprintf(b, "Registered from `%s`.\n\n", c.Package)
	}
	b.WriteString("```php\n")
	writeComment(b, c.Comment, "")
	fmt.Fprintf(b, "class %s\n{\n", c.Name)
	fmt.Fprintf(b, "    public function __construct(%s) {}\n", paramList(c.Params))
	for _, m := range c.Methods {
		b.WriteString("\n")
		writeComment(b, m.Comment, "    ")
		fmt.Fprintf(b, "    public function %s(%s): %s {}\n", m.Name, paramList(m.Params), m.Returns)
	}
	b.WriteString("}\n```\n\n")
	if len(c.Aliases) > 0 {
		fmt.Fprintf(b, "Also registered with this constructor: `%s`.\n\n",
			strings.Join(c.Aliases, "`, `"))
	}
}

// writeComment writes a doc comment in PHP form: one line as a line comment,
// more as a docblock.
func writeComment(b *strings.Builder, lines []string, indent string) {
	switch len(lines) {
	case 0:
	case 1:
		fmt.Fprintf(b, "%s// %s\n", indent, lines[0])
	default:
		fmt.Fprintf(b, "%s/**\n", indent)
		for _, line := range lines {
			fmt.Fprintf(b, "%s * %s\n", indent, strings.TrimRight(line, " "))
		}
		fmt.Fprintf(b, "%s */\n", indent)
	}
}

// paramList renders parameters in signature order.
func paramList(params []Param) string {
	parts := make([]string, 0, len(params))
	for _, p := range params {
		parts = append(parts, renderParam(p))
	}
	return strings.Join(parts, ", ")
}

// renderParam renders one parameter: `int $num`, `string ...$args`, or the
// by-reference form `&$ref = null` (optional when the Go side is variadic).
func renderParam(p Param) string {
	if p.ByRef {
		if p.Variadic {
			return "&$" + p.Name + " = null"
		}
		return "&$" + p.Name
	}
	sep := " $"
	if p.Variadic {
		sep = " ...$"
	}
	return p.Type + sep + p.Name
}
