#!/usr/bin/env phpscript
<?php

$functions = get_defined_functions();
$classes = get_declared_classes();
$groups = array(
    "Arrays" => "array_",
    "Strings" => "str",
    "JSON" => "json_",
    "Regular expressions" => "preg_",
    "Filesystem" => "file_",
    "Type checks" => "is_",
    "Runtime introspection" => "get_",
    "SPL and autoloading" => "spl_",
);
$grouped_functions = array();

echo "# Implemented PHP APIs\n\n";
echo "<!-- Generated by: phpscript scripts/list-apis.php > docs/reference/extensions/implemented-apis.md -->\n\n";
echo "This file lists PHP functions and classes registered by the standard phpscript CLI runtime.\n";
echo "Regenerate it after changing runtime or standard-library registrations.\n\n";

foreach ($groups as $title => $prefix) {
    echo "## " . $title . "\n\n";
    foreach ($functions["internal"] as $function) {
        if (strpos($function, $prefix) === 0) {
            echo "- `" . $function . "`\n";
            $grouped_functions[] = $function;
        }
    }
    echo "\n";
}

echo "## Other\n\n";
foreach ($functions["internal"] as $function) {
    if (!in_array($function, $grouped_functions)) {
        echo "- `" . $function . "`\n";
    }
}
echo "\n";

echo "## Classes\n\n";
foreach ($classes as $class) {
    echo "- `" . $class . "`\n";
}
