package ps

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/titpetric/pdo/client"

	"github.com/titpetric/phpscript/model"
	"github.com/titpetric/phpscript/stdlib/status"
)

// DatabaseClient adds request tracing to the database client binding.
type DatabaseClient struct {
	DatabaseClient *client.Bridge
	ID             string
}

type databaseClientSpanKey struct{}

// SetID records the PHP variable receiving this constructed client.
func (b *DatabaseClient) SetID(id string) {
	b.ID = id
}

// Insert inserts a dynamically typed named value.
func (b *DatabaseClient) Insert(ctx context.Context, table string, value any) (any, error) {
	return b.DatabaseClient.Insert(b.withSpan(ctx, "Insert"), table, value)
}

// Replace replaces a row using a dynamically typed named value.
func (b *DatabaseClient) Replace(ctx context.Context, table string, value any) (any, error) {
	return b.DatabaseClient.Replace(b.withSpan(ctx, "Replace"), table, value)
}

// Update updates a row using dynamically typed named values and key columns.
func (b *DatabaseClient) Update(ctx context.Context, table string, value any, keyColumns ...any) (any, error) {
	return b.DatabaseClient.Update(b.withSpan(ctx, "Update"), table, value, keyColumns...)
}

// Query executes a statement with dynamically typed arguments.
func (b *DatabaseClient) Query(ctx context.Context, query string, args ...any) (any, error) {
	return b.DatabaseClient.Query(b.withSpan(ctx, "Query"), query, args...)
}

// Get returns the first result row.
func (b *DatabaseClient) Get(ctx context.Context, query string, args ...any) (any, error) {
	value, err := b.DatabaseClient.Get(b.withSpan(ctx, "Get"), query, args...)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	return databaseClientValue(value), err
}

// GetAll returns all result rows.
func (b *DatabaseClient) GetAll(ctx context.Context, query string, args ...any) (any, error) {
	value, err := b.DatabaseClient.GetAll(b.withSpan(ctx, "GetAll"), query, args...)
	return databaseClientValue(value), err
}

// Connect reserves an exclusive connection from the pool.
func (b *DatabaseClient) Connect(ctx context.Context) (any, error) {
	b.span(ctx, "Connect")
	return b.DatabaseClient.Connect(ctx)
}

// Close releases an exclusive connection back to the pool.
func (b *DatabaseClient) Close(ctx context.Context) (any, error) {
	b.span(ctx, "Close")
	return b.DatabaseClient.Close(ctx)
}

// Begin starts a transaction and opens its tracing span.
func (b *DatabaseClient) Begin(ctx context.Context) (any, error) {
	b.span(ctx, "Begin", status.OpenSpan)
	return b.DatabaseClient.Begin(ctx)
}

// Rollback rolls back the active transaction and closes its tracing span.
func (b *DatabaseClient) Rollback(ctx context.Context) (any, error) {
	b.span(ctx, "Rollback", status.CloseSpan)
	return b.DatabaseClient.Rollback(ctx)
}

// Commit commits the active transaction and closes its tracing span.
func (b *DatabaseClient) Commit(ctx context.Context) (any, error) {
	b.span(ctx, "Commit", status.CloseSpan)
	return b.DatabaseClient.Commit(ctx)
}

// InsertID returns the ID generated by the last insert.
func (b *DatabaseClient) InsertID(ctx context.Context) (any, error) {
	b.span(ctx, "InsertID")
	return b.DatabaseClient.InsertID(ctx)
}

// RowsAffected returns the affected row count from the last write.
func (b *DatabaseClient) RowsAffected(ctx context.Context) (any, error) {
	b.span(ctx, "RowsAffected")
	return b.DatabaseClient.RowsAffected(ctx)
}

func (b *DatabaseClient) observe(ctx context.Context, entry client.QueryLogEntry) {
	span, _ := ctx.Value(databaseClientSpanKey{}).(*status.RequestSpan)
	if span != nil {
		span.SetMessage(fmt.Sprintf("%s: <code>%s</code>", span.Message, entry.Query))
		span.SetTime(entry.Started)
		span.SetDuration(entry.Duration)
		span.SetAttribute("transaction_depth", entry.TxDepth)
		if entry.Err != nil {
			span.RecordError(entry.Err)
		}
	}
}

func (b *DatabaseClient) span(ctx context.Context, method string, flags ...status.Flag) *status.RequestSpan {
	if b.ID != "" {
		method = b.ID + "." + method
	}
	return status.StartSpan(ctx, method, append([]status.Flag{status.SpanType.Database}, flags...)...)
}

func (b *DatabaseClient) withSpan(ctx context.Context, method string) context.Context {
	span := b.span(ctx, method)
	if span == nil {
		return ctx
	}
	return context.WithValue(ctx, databaseClientSpanKey{}, span)
}

func databaseClientValue(value any) any {
	switch value := value.(type) {
	case map[string]any:
		result := model.NewArray()
		for key, item := range value {
			result.Set(key, databaseClientValue(item))
		}
		return result
	case []map[string]any:
		result := model.NewArray()
		for _, item := range value {
			result.Append(databaseClientValue(item))
		}
		return result
	default:
		return value
	}
}
