package ps

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/titpetric/pdo/client"

	"github.com/titpetric/phpscript/stdlib/status"
)

// Database adds request tracing to the database binding.
type Database struct {
	Bridge *client.Bridge
	ID     string
}

type databaseSpanKey struct{}

// SetID records the PHP variable receiving this constructed client.
func (b *Database) SetID(id string) {
	b.ID = id
}

// Insert inserts a dynamically typed named value.
func (b *Database) Insert(ctx context.Context, table string, value any) (any, error) {
	return b.Bridge.Insert(b.withSpan(ctx, "Insert"), table, value)
}

// Replace replaces a row using a dynamically typed named value.
func (b *Database) Replace(ctx context.Context, table string, value any) (any, error) {
	return b.Bridge.Replace(b.withSpan(ctx, "Replace"), table, value)
}

// Update updates a row using dynamically typed named values and key columns.
func (b *Database) Update(ctx context.Context, table string, value any, keyColumns ...any) (any, error) {
	return b.Bridge.Update(b.withSpan(ctx, "Update"), table, value, keyColumns...)
}

// Query executes a statement with dynamically typed arguments.
func (b *Database) Query(ctx context.Context, query string, args ...any) (any, error) {
	return b.Bridge.Query(b.withSpan(ctx, "Query"), query, args...)
}

// Get returns the first result row.
//
// Rows reach PHP as the bridge produced them — a map[string]any per row, a
// []map[string]any per result set — rather than being copied into a
// *model.Array. The VM reads both natively: foreach walks them, $row["col"]
// indexes them, and $row["extra"] = 1 writes to them, since a Go map is a
// reference type. The copy cost two allocations plus an interface box per
// column on every row of every query.
//
// The one thing a map does not carry is column order, and neither did the
// *model.Array: the bridge's map had already lost it, so
// `foreach ($row as $column => $value)` has always produced an arbitrary order.
// It is now arbitrary per iteration rather than fixed per row; scripts that
// need a stable order should name their columns in the SELECT and index them.
func (b *Database) Get(ctx context.Context, query string, args ...any) (any, error) {
	value, err := b.Bridge.Get(b.withSpan(ctx, "Get"), query, args...)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	return value, err
}

// GetAll returns all result rows. See Get for the row representation.
func (b *Database) GetAll(ctx context.Context, query string, args ...any) (any, error) {
	return b.Bridge.GetAll(b.withSpan(ctx, "GetAll"), query, args...)
}

// Connect reserves an exclusive connection from the pool.
func (b *Database) Connect(ctx context.Context) (any, error) {
	b.span(ctx, "Connect")
	return b.Bridge.Connect(ctx)
}

// Close releases an exclusive connection back to the pool.
func (b *Database) Close(ctx context.Context) (any, error) {
	b.span(ctx, "Close")
	return b.Bridge.Close(ctx)
}

// Begin starts a transaction and opens its tracing span.
func (b *Database) Begin(ctx context.Context) (any, error) {
	b.span(ctx, "Begin", status.OpenSpan)
	return b.Bridge.Begin(ctx)
}

// Rollback rolls back the active transaction and closes its tracing span.
func (b *Database) Rollback(ctx context.Context) (any, error) {
	b.span(ctx, "Rollback", status.CloseSpan)
	return b.Bridge.Rollback(ctx)
}

// Commit commits the active transaction and closes its tracing span.
func (b *Database) Commit(ctx context.Context) (any, error) {
	b.span(ctx, "Commit", status.CloseSpan)
	return b.Bridge.Commit(ctx)
}

// InsertID returns the ID generated by the last insert.
func (b *Database) InsertID(ctx context.Context) (any, error) {
	b.span(ctx, "InsertID")
	return b.Bridge.InsertID(ctx)
}

// RowsAffected returns the affected row count from the last write.
func (b *Database) RowsAffected(ctx context.Context) (any, error) {
	b.span(ctx, "RowsAffected")
	return b.Bridge.RowsAffected(ctx)
}

func (b *Database) observe(ctx context.Context, entry client.QueryLogEntry) {
	span, _ := ctx.Value(databaseSpanKey{}).(*status.RequestSpan)
	if span != nil {
		span.SetMessage(fmt.Sprintf("%s: <code>%s</code>", span.Message, entry.Query))
		span.SetTime(entry.Started)
		span.SetDuration(entry.Duration)
		span.SetAttribute("transaction_depth", entry.TxDepth)
		if entry.Err != nil {
			span.RecordError(entry.Err)
		}
	}
}

func (b *Database) span(ctx context.Context, method string, flags ...status.Flag) *status.RequestSpan {
	if b.ID != "" {
		method = b.ID + "." + method
	}
	return status.StartSpan(ctx, method, append([]status.Flag{status.SpanType.Database}, flags...)...)
}

func (b *Database) withSpan(ctx context.Context, method string) context.Context {
	span := b.span(ctx, method)
	if span == nil {
		return ctx
	}
	return context.WithValue(ctx, databaseSpanKey{}, span)
}
